<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="USER-PC" name="com.selenium.web.sanity.ATnTHomeTest" tests="1" failures="1" timestamp="4 May 2016 08:57:16 GMT" time="40.796" errors="0">
  <testcase name="Clicking_PrimaryNav_AllLinks" time="40.796" classname="com.selenium.web.sanity.ATnTHomeTest">
    <failure type="java.lang.AssertionError" message="test case one failed verifying home page links expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: test case one failed verifying home page links expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.selenium.web.sanity.ATnTHomeTest.Clicking_PrimaryNav_AllLinks(ATnTHomeTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Clicking_PrimaryNav_AllLinks -->
</testsuite> <!-- com.selenium.web.sanity.ATnTHomeTest -->
